# Generated by Django 5.1.3 on 2024-12-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_class_intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='new_field_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='new_field_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
