# Generated by Django 5.1.3 on 2024-12-03 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_class_intake', '0004_form_frequency_alter_form_alarm_alter_form_carryaway_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='risk_class_intake.form')),
            ],
        ),
    ]
