# Generated by Django 5.1.3 on 2024-12-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_class_intake', '0005_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
