# Generated by Django 5.1.3 on 2024-12-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_class_intake', '0006_alter_form_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attractiveness',
            field=models.CharField(default='L', max_length=2),
        ),
    ]
